In [46]:
import pandas as pd

In [47]:
df = pd.read_csv('airline_passenger_satisfaction_practice.csv')
df.head()

,Passenger_ID,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Seat comfort,Food and drink,Departure Delay in Minutes,Arrival Delay in Minutes,Satisfaction
0,1,Male,Loyal customer,66,Personal Travel,Eco,4899,3,2,5,48.0,53.0,satisfied
1,2,Female,Loyal customer,63,Business travel,Business,4977,2,2,2,24.0,14.0,Satisfied
2,3,Male,Loyal Customer,25,Personal Travel,Business,4100,1,5,1,23.0,32.0,Neutral or Dissatisfied
3,4,Male,Loyal Customer,48,Personal Travel,Business,723,5,5,4,11.0,6.0,satisfied
4,5,Male,disloyal customer,52,Business travel,Eco Plus,2593,4,2,4,17.0,11.0,Neutral or Dissatisfied

In [48]:
df_business = df[df['Class']=='Business'].copy()

In [49]:
df_business.shape

(76, 13)

In [50]:
df_business.info()

<class 'pandas.core.frame.DataFrame'>
Index: 76 entries, 1 to 203
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Passenger_ID                76 non-null     int64
 1   Gender                      76 non-null     object
 2   Customer Type               76 non-null     object
 3   Age                         76 non-null     object
 4   Type of Travel              76 non-null     object
 5   Class                       76 non-null     object
 6   Flight Distance             76 non-null     int64
 7   Inflight wifi service       76 non-null     int64
 8   Seat comfort                76 non-null     int64
 9   Food and drink              76 non-null     int64
 10  Departure Delay in Minutes  76 non-null     float64
 11  Arrival Delay in Minutes    74 non-null     float64
 12  Satisfaction                64 non-null     object
dtypes: float64(2), int64(5), object(6)
memory usage: 8.3+ KB

In [51]:
df_business.isnull().sum()

Passenger_ID                   0
Gender                         0
Customer Type                  0
Age                            0
Type of Travel                 0
Class                          0
Flight Distance                0
Inflight wifi service          0
Seat comfort                   0
Food and drink                 0
Departure Delay in Minutes     0
Arrival Delay in Minutes       2
Satisfaction                  12
dtype: int64

In [52]:
print(df['Class'].unique())

['Eco' 'Business' 'Eco Plus']

In [53]:
df_business = df[df['Class'].str.strip().str.lower()=='business']

In [54]:
print('missing value',df_business.isnull().sum().sum())

missing value 14

In [55]:
print('duplicate value',df_business.duplicated().sum())

duplicate value 3

In [56]:
df_business['Class'].unique()

array(['Business'], dtype=object)

In [57]:
df_business['Class'].shape

(76,)

In [58]:
print('rows: ',df_business.shape[0])
print('columns: ',df_business.shape[1])

rows:  76
columns:  13

In [59]:
print(df_business.columns.tolist())

['Passenger_ID', 'Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class', 'Flight Distance', 'Inflight wifi service', 'Seat comfort', 'Food and drink', 'Departure Delay in Minutes', 'Arrival Delay in Minutes', 'Satisfaction']

In [60]:
df_business.dtypes

Passenger_ID                    int64
Gender                         object
Customer Type                  object
Age                            object
Type of Travel                 object
Class                          object
Flight Distance                 int64
Inflight wifi service           int64
Seat comfort                    int64
Food and drink                  int64
Departure Delay in Minutes    float64
Arrival Delay in Minutes      float64
Satisfaction                   object
dtype: object

In [61]:
df_business.info()

<class 'pandas.core.frame.DataFrame'>
Index: 76 entries, 1 to 203
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Passenger_ID                76 non-null     int64
 1   Gender                      76 non-null     object
 2   Customer Type               76 non-null     object
 3   Age                         76 non-null     object
 4   Type of Travel              76 non-null     object
 5   Class                       76 non-null     object
 6   Flight Distance             76 non-null     int64
 7   Inflight wifi service       76 non-null     int64
 8   Seat comfort                76 non-null     int64
 9   Food and drink              76 non-null     int64
 10  Departure Delay in Minutes  76 non-null     float64
 11  Arrival Delay in Minutes    74 non-null     float64
 12  Satisfaction                64 non-null     object
dtypes: float64(2), int64(5), object(6)
memory usage: 8.3+ KB

In [62]:
missing = df_business.isnull().sum()
print(missing[missing > 0])
print('total missing value',df_business.isnull().sum().sum())

Arrival Delay in Minutes     2
Satisfaction                12
dtype: int64
total missing value 14

In [63]:
cols = ["Customer Type", "Satisfaction", "Gender", "Type of Travel"]

for col in cols:
    print(f"\nUnique values in {col}:")
    print(df_business[col].unique())

Unique values in Customer Type:
['Loyal customer' 'Loyal Customer' 'disloyal customer']

Unique values in Satisfaction:
['Satisfied' 'Neutral or Dissatisfied' 'satisfied' nan]

Unique values in Gender:
['Female' 'Male']

Unique values in Type of Travel:
['Business travel' 'Personal Travel']

In [64]:
for col in cols:
    print(f"\nValue counts of {col}:")
    print(df_business[col].value_counts())

Value counts of Customer Type:
Customer Type
Loyal Customer       30
Loyal customer       27
disloyal customer    19
Name: count, dtype: int64

Value counts of Satisfaction:
Satisfaction
satisfied                  24
Satisfied                  22
Neutral or Dissatisfied    18
Name: count, dtype: int64

Value counts of Gender:
Gender
Female    41
Male      35
Name: count, dtype: int64

Value counts of Type of Travel:
Type of Travel
Business travel    43
Personal Travel    33
Name: count, dtype: int64

In [65]:
for col in cols:
    print(f"\nCleaned unique values in {col}:")
    print(df_business[col].str.strip().str.lower().unique())

Cleaned unique values in Customer Type:
['loyal customer' 'disloyal customer']

Cleaned unique values in Satisfaction:
['satisfied' 'neutral or dissatisfied' nan]

Cleaned unique values in Gender:
['female' 'male']

Cleaned unique values in Type of Travel:
['business travel' 'personal travel']

In [66]:
df_business.duplicated().sum()

np.int64(3)

In [67]:
df_business.drop(columns=["Class"], inplace=True)

C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\1073076961.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_business.drop(columns=["Class"], inplace=True)

In [68]:
df_business.columns = df_business.columns.str.lower().str.replace(" ", "_")

df_business.columns

Index(['passenger_id', 'gender', 'customer_type', 'age', 'type_of_travel',
       'flight_distance', 'inflight_wifi_service', 'seat_comfort',
       'food_and_drink', 'departure_delay_in_minutes',
       'arrival_delay_in_minutes', 'satisfaction'],
      dtype='object')

In [69]:
df_business["age"] = pd.to_numeric(df_business["age"], errors="coerce")

C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\203539828.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_business["age"] = pd.to_numeric(df_business["age"], errors="coerce")

In [70]:
df_business["customer_type"] = df_business["customer_type"].str.lower()
df_business["satisfaction"] = df_business["satisfaction"].str.lower()
df_business["type_of_travel"] = df_business["type_of_travel"].str.lower()
df_business["gender"] = df_business["gender"].str.lower()

C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\3095854073.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_business["customer_type"] = df_business["customer_type"].str.lower()
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\3095854073.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_business["satisfaction"] = df_business["satisfaction"].str.lower()
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\3095854073.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_business["type_of_travel"] = df_business["type_of_travel"].str.lower()
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\3095854073.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_business["gender"] = df_business["gender"].str.lower()

In [71]:
df_business.isnull().sum()

passenger_id                   0
gender                         0
customer_type                  0
age                            3
type_of_travel                 0
flight_distance                0
inflight_wifi_service          0
seat_comfort                   0
food_and_drink                 0
departure_delay_in_minutes     0
arrival_delay_in_minutes       2
satisfaction                  12
dtype: int64

In [72]:
num_cols = df_business.select_dtypes(include=["float64", "int64"]).columns

for col in num_cols:
    df_business[col].fillna(df_business[col].median(), inplace=True)

C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\2887027155.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_business[col].fillna(df_business[col].median(), inplace=True)
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\2887027155.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_business[col].fillna(df_business[col].median(), inplace=True)
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\2887027155.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_business[col].fillna(df_business[col].median(), inplace=True)
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\2887027155.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_business[col].fillna(df_business[col].median(), inplace=True)
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\2887027155.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_business[col].fillna(df_business[col].median(), inplace=True)
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\2887027155.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_business[col].fillna(df_business[col].median(), inplace=True)
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\2887027155.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_business[col].fillna(df_business[col].median(), inplace=True)
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\2887027155.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_business[col].fillna(df_business[col].median(), inplace=True)
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\2887027155.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_business[col].fillna(df_business[col].median(), inplace=True)
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\2887027155.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_business[col].fillna(df_business[col].median(), inplace=True)
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\2887027155.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_business[col].fillna(df_business[col].median(), inplace=True)
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\2887027155.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_business[col].fillna(df_business[col].median(), inplace=True)
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\2887027155.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_business[col].fillna(df_business[col].median(), inplace=True)
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\2887027155.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_business[col].fillna(df_business[col].median(), inplace=True)
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\2887027155.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_business[col].fillna(df_business[col].median(), inplace=True)
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\2887027155.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_business[col].fillna(df_business[col].median(), inplace=True)

In [73]:
cat_cols = df_business.select_dtypes(include=["object"]).columns

for col in cat_cols:
    df_business[col].fillna(df_business[col].mode()[0], inplace=True)

C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\2213899820.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_business[col].fillna(df_business[col].mode()[0], inplace=True)
C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\2213899820.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_business[col].fillna(df_business[col].mode()[0], inplace=True)

In [74]:
df_business.drop_duplicates(inplace=True)

C:\Users\MasteR\AppData\Local\Temp\ipykernel_1732\3124999115.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_business.drop_duplicates(inplace=True)

In [75]:
df_business.info()

<class 'pandas.core.frame.DataFrame'>
Index: 73 entries, 1 to 196
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   passenger_id                73 non-null     int64
 1   gender                      73 non-null     object
 2   customer_type               73 non-null     object
 3   age                         73 non-null     float64
 4   type_of_travel              73 non-null     object
 5   flight_distance             73 non-null     int64
 6   inflight_wifi_service       73 non-null     int64
 7   seat_comfort                73 non-null     int64
 8   food_and_drink              73 non-null     int64
 9   departure_delay_in_minutes  73 non-null     float64
 10  arrival_delay_in_minutes    73 non-null     float64
 11  satisfaction                73 non-null     object
dtypes: float64(3), int64(5), object(4)
memory usage: 7.4+ KB

In [76]:
df_business.isnull().sum()

passenger_id                  0
gender                        0
customer_type                 0
age                           0
type_of_travel                0
flight_distance               0
inflight_wifi_service         0
seat_comfort                  0
food_and_drink                0
departure_delay_in_minutes    0
arrival_delay_in_minutes      0
satisfaction                  0
dtype: int64

In [77]:
df_business.to_csv("Project_2_Group1.csv", index=False)

In [78]:
before_info = df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Passenger_ID                205 non-null    int64
 1   Gender                      205 non-null    object
 2   Customer Type               205 non-null    object
 3   Age                         205 non-null    object
 4   Type of Travel              205 non-null    object
 5   Class                       205 non-null    object
 6   Flight Distance             205 non-null    int64
 7   Inflight wifi service       205 non-null    int64
 8   Seat comfort                205 non-null    int64
 9   Food and drink              205 non-null    int64
 10  Departure Delay in Minutes  203 non-null    float64
 11  Arrival Delay in Minutes    201 non-null    float64
 12  Satisfaction                164 non-null    object
dtypes: float64(2), int64(5), object(6)
memory usage: 20.9+ KB

In [79]:
after_info = df_business.info()

<class 'pandas.core.frame.DataFrame'>
Index: 73 entries, 1 to 196
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   passenger_id                73 non-null     int64
 1   gender                      73 non-null     object
 2   customer_type               73 non-null     object
 3   age                         73 non-null     float64
 4   type_of_travel              73 non-null     object
 5   flight_distance             73 non-null     int64
 6   inflight_wifi_service       73 non-null     int64
 7   seat_comfort                73 non-null     int64
 8   food_and_drink              73 non-null     int64
 9   departure_delay_in_minutes  73 non-null     float64
 10  arrival_delay_in_minutes    73 non-null     float64
 11  satisfaction                73 non-null     object
dtypes: float64(3), int64(5), object(4)
memory usage: 7.4+ KB

In [82]:
comparison = pd.DataFrame({
    "Column": df_business.columns,
    "Datatype_After": df_business.dtypes.values,
    "Missing_Values_After": df_business.isnull().sum().values,
    "Unique_Values_After": [df_business[col].nunique() for col in df_business.columns]
})

comparison

,Column,Datatype_After,Missing_Values_After,Unique_Values_After
0,passenger_id,int64,0,73
1,gender,object,0,2
2,customer_type,object,0,2
3,age,float64,0,38
4,type_of_travel,object,0,2
5,flight_distance,int64,0,73
6,inflight_wifi_service,int64,0,5
7,seat_comfort,int64,0,5
8,food_and_drink,int64,0,5
9,departure_delay_in_minutes,float64,0,41
10,arrival_delay_in_minutes,float64,0,44
11,satisfaction,object,0,2